const express=require('express');const path=require('path');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const session=require('express-session');
const app=express();const db=new Database('stockflow.db');db.pragma('foreign_keys = ON');
app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'stockflow-academico-2026',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}}));
db.exec(`CREATE TABLE IF NOT EXISTS usuarios(id INTEGER PRIMARY KEY AUTOINCREMENT,nome TEXT NOT NULL,email TEXT UNIQUE NOT NULL,senha TEXT NOT NULL,perfil TEXT DEFAULT 'admin',criado_em TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categorias(id INTEGER PRIMARY KEY AUTOINCREMENT,nome TEXT UNIQUE NOT NULL,criado_em TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS produtos(id INTEGER PRIMARY KEY AUTOINCREMENT,nome TEXT NOT NULL,categoria_id INTEGER NOT NULL,preco REAL NOT NULL DEFAULT 0,estoque INTEGER NOT NULL DEFAULT 0,imagem TEXT,criado_em TEXT DEFAULT CURRENT_TIMESTAMP,atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(categoria_id) REFERENCES categorias(id));
CREATE TABLE IF NOT EXISTS historico(id INTEGER PRIMARY KEY AUTOINCREMENT,usuario_id INTEGER,produto_id INTEGER,acao TEXT NOT NULL,detalhes TEXT,criado_em TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(usuario_id) REFERENCES usuarios(id),FOREIGN KEY(produto_id) REFERENCES produtos(id));`);
const admin=db.prepare('SELECT id FROM usuarios WHERE email=?').get('admin@stockflow.local');if(!admin){const hash=bcrypt.hashSync('admin123',10);db.prepare('INSERT INTO usuarios(nome,email,senha,perfil) VALUES(?,?,?,?)').run('Administrador','admin@stockflow.local',hash,'admin')}
for(const c of ['Eletrônicos','Casa','Moda','Beleza','Esportes','Livros'])db.prepare('INSERT OR IGNORE INTO categorias(nome) VALUES(?)').run(c);
function auth(req,res,next){if(!req.session.user)return res.status(401).json({erro:'Não autenticado'});next()}
function cleanText(v,max=80){return typeof v==='string'?v.trim().slice(0,max):''}
function productData(body){const nome=cleanText(body.nome);const categoria_id=Number(body.categoria_id);const preco=Number(body.preco);const estoque=Number(body.estoque);const imagem=cleanText(body.imagem,500);if(!nome||!Number.isInteger(categoria_id)||categoria_id<1||!Number.isFinite(preco)||preco<0||!Number.isInteger(estoque)||estoque<0)throw new Error('Dados do produto inválidos');if(imagem&&!/^https?:\\/\\//i.test(imagem))throw new Error('A imagem deve usar uma URL http/https');return {nome,categoria_id,preco,estoque,imagem}}
function log(user,product,action,details){db.prepare('INSERT INTO historico(usuario_id,produto_id,acao,detalhes) VALUES(?,?,?,?)').run(user,product||null,action,details||'')}
app.post('/api/login',(req,res)=>{const email=cleanText(req.body.email,160).toLowerCase();const u=db.prepare('SELECT * FROM usuarios WHERE email=?').get(email);if(!u||!bcrypt.compareSync(req.body.senha||'',u.senha))return res.status(401).json({erro:'E-mail ou senha inválidos'});req.session.user={id:u.id,nome:u.nome,email:u.email,perfil:u.perfil};res.json({sucesso:true,usuario:req.session.user})});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({sucesso:true})));app.get('/api/me',(req,res)=>res.json({autenticado:!!req.session.user,usuario:req.session.user||null}));
app.get('/api/categorias',auth,(req,res)=>res.json(db.prepare('SELECT * FROM categorias ORDER BY nome').all()));
app.post('/api/categorias',auth,(req,res)=>{try{const nome=cleanText(req.body.nome,40);if(!nome)throw Error();const r=db.prepare('INSERT INTO categorias(nome) VALUES(?)').run(nome);log(req.session.user.id,null,'CATEGORIA_CRIADA',nome);res.status(201).json({id:r.lastInsertRowid,nome})}catch(e){res.status(400).json({erro:'Categoria já existe ou é inválida'})}});
app.delete('/api/categorias/:id',auth,(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({erro:'ID inválido'});const used=db.prepare('SELECT COUNT(*) n FROM produtos WHERE categoria_id=?').get(id).n;if(used)return res.status(400).json({erro:'Categoria possui produtos e não pode ser excluída'});const r=db.prepare('DELETE FROM categorias WHERE id=?').run(id);if(!r.changes)return res.status(404).json({erro:'Categoria não encontrada'});log(req.session.user.id,null,'CATEGORIA_EXCLUIDA',String(id));res.json({sucesso:true})});
app.get('/api/produtos',auth,(req,res)=>res.json(db.prepare('SELECT p.*,c.nome categoria FROM produtos p JOIN categorias c ON c.id=p.categoria_id ORDER BY p.id DESC').all()));
app.post('/api/produtos',auth,(req,res)=>{try{const d=productData(req.body);if(!db.prepare('SELECT id FROM categorias WHERE id=?').get(d.categoria_id))return res.status(400).json({erro:'Categoria não encontrada'});const r=db.prepare('INSERT INTO produtos(nome,categoria_id,preco,estoque,imagem) VALUES(?,?,?,?,?)').run(d.nome,d.categoria_id,d.preco,d.estoque,d.imagem);log(req.session.user.id,r.lastInsertRowid,'PRODUTO_CRIADO',d.nome);res.status(201).json({id:r.lastInsertRowid})}catch(e){res.status(400).json({erro:e.message||'Dados inválidos'})}});
app.put('/api/produtos/:id',auth,(req,res)=>{try{const id=Number(req.params.id);const old=db.prepare('SELECT * FROM produtos WHERE id=?').get(id);if(!old)return res.status(404).json({erro:'Produto não encontrado'});const d=productData(req.body);if(!db.prepare('SELECT id FROM categorias WHERE id=?').get(d.categoria_id))return res.status(400).json({erro:'Categoria não encontrada'});db.prepare('UPDATE produtos SET nome=?,categoria_id=?,preco=?,estoque=?,imagem=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?').run(d.nome,d.categoria_id,d.preco,d.estoque,d.imagem,id);log(req.session.user.id,id,'PRODUTO_ALTERADO',d.nome);res.json({sucesso:true})}catch(e){res.status(400).json({erro:e.message||'Dados inválidos'})}});
app.delete('/api/produtos/:id',auth,(req,res)=>{const id=Number(req.params.id);const p=db.prepare('SELECT * FROM produtos WHERE id=?').get(id);if(!p)return res.status(404).json({erro:'Produto não encontrado'});db.prepare('DELETE FROM produtos WHERE id=?').run(id);log(req.session.user.id,id,'PRODUTO_EXCLUIDO',p.nome);res.json({sucesso:true})});
app.patch('/api/produtos/:id/estoque',auth,(req,res)=>{const id=Number(req.params.id),novo=Number(req.body.estoque),p=db.prepare('SELECT * FROM produtos WHERE id=?').get(id);if(!p||!Number.isInteger(novo)||novo<0)return res.status(400).json({erro:'Estoque inválido'});db.prepare('UPDATE produtos SET estoque=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?').run(novo,id);log(req.session.user.id,id,'ESTOQUE_ATUALIZADO',p.estoque+' → '+novo);res.json({sucesso:true})});
app.get('/api/dashboard',auth,(req,res)=>{const total=db.prepare('SELECT COUNT(*) n FROM produtos').get().n;const estoque=db.prepare('SELECT COALESCE(SUM(estoque),0) n FROM produtos').get().n;const valor=db.prepare('SELECT COALESCE(SUM(estoque*preco),0) n FROM produtos').get().n;const categorias=db.prepare('SELECT c.nome,COUNT(p.id) quantidade FROM categorias c LEFT JOIN produtos p ON p.categoria_id=c.id GROUP BY c.id ORDER BY quantidade DESC,c.nome').all();const baixos=db.prepare('SELECT p.id,p.nome,p.estoque,c.nome categoria FROM produtos p JOIN categorias c ON c.id=p.categoria_id WHERE p.estoque<=5 ORDER BY p.estoque').all();res.json({total,estoque,valor,categorias,baixos})});
app.get('/api/historico',auth,(req,res)=>res.json(db.prepare('SELECT h.*,u.nome usuario,p.nome produto FROM historico h LEFT JOIN usuarios u ON u.id=h.usuario_id LEFT JOIN produtos p ON p.id=h.produto_id ORDER BY h.id DESC LIMIT 100').all()));
app.use(express.static(path.join(__dirname,'.')));app.use((err,req,res,next)=>{console.error(err);res.status(500).json({erro:'Erro interno do servidor'})});
const PORT=Number(process.env.PORT)||3000;app.listen(PORT,()=>console.log('StockFlow em http://localhost:'+PORT));